# 02 — Retrieval Evaluation

Evaluates minsearch, FAISS, and RRF across:
- 2 ground truth files: `gpt-5.4-mini`, `gpt-5.6-luna`
- 2 embedding models: `all-MiniLM-L6-v2`, `multi-qa-MiniLM-L6-cos-v1`

Saves all results to `data/retrieval-eval-results.csv`.

In [1]:
import sys, os, importlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT / 'pyproject.toml').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

import pandas as pd
from dotenv import load_dotenv
from tqdm.auto import tqdm

load_dotenv(ROOT / '.envrc')

True

In [2]:
def hit_rate_mrr(search_fn, ground_truth, num_results=10):
    hits = 0
    mrr_sum = 0.0
    for _, row in tqdm(ground_truth.iterrows(), total=len(ground_truth), leave=False):
        results = search_fn(row['question'], num_results=num_results)
        result_ids = [str(r['id']) for r in results]
        expected = str(row['movie_id'])
        if expected in result_ids:
            hits += 1
            rank = result_ids.index(expected) + 1
            mrr_sum += 1 / rank
    n = len(ground_truth)
    return round(hits / n, 4), round(mrr_sum / n, 4)

In [3]:
GT_MODELS = ['gpt-5.4-mini', 'gpt-5.6-luna']
EMBEDDING_MODELS = [
    'sentence-transformers/all-MiniLM-L6-v2',
    'sentence-transformers/multi-qa-MiniLM-L6-cos-v1',
]

all_rows = []

for gt_model in GT_MODELS:
    gt = pd.read_csv(ROOT / f'data/ground-truth-retrieval-{gt_model}.csv')
    print(f'\n=== Ground truth: {gt_model} ({len(gt)} pairs) ===')

    for emb_model in EMBEDDING_MODELS:
        print(f'  Loading indexes with {emb_model} ...')
        os.environ['EMBEDDING_MODEL'] = emb_model

        # Reload ingest to rebuild FAISS with the current embedding model
        import movie_assistant.ingest as ingest
        importlib.reload(ingest)

        emb_short = emb_model.split('/')[-1]

        print(f'  minsearch ...')
        hr, mrr = hit_rate_mrr(ingest.search_minsearch, gt)
        all_rows.append({'gt_model': gt_model, 'embedding': emb_short, 'method': 'minsearch', 'hit_rate': hr, 'mrr': mrr})
        print(f'    hit_rate={hr}, mrr={mrr}')

        print(f'  FAISS ({emb_short}) ...')
        hr, mrr = hit_rate_mrr(ingest.search_faiss, gt)
        all_rows.append({'gt_model': gt_model, 'embedding': emb_short, 'method': 'faiss', 'hit_rate': hr, 'mrr': mrr})
        print(f'    hit_rate={hr}, mrr={mrr}')

        print(f'  RRF ...')
        hr, mrr = hit_rate_mrr(ingest.search_rrf, gt)
        all_rows.append({'gt_model': gt_model, 'embedding': emb_short, 'method': 'rrf', 'hit_rate': hr, 'mrr': mrr})
        print(f'    hit_rate={hr}, mrr={mrr}')

results_df = pd.DataFrame(all_rows)
out = ROOT / 'data/retrieval-eval-results.csv'
results_df.to_csv(out, index=False)
print(f'\nSaved to {out}')

=== Ground truth: gpt-5.4-mini (6000 pairs) ===
  Loading indexes with sentence-transformers/all-MiniLM-L6-v2 ...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

  minsearch ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.3493, mrr=0.1699
  FAISS (all-MiniLM-L6-v2) ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.5407, mrr=0.3379
  RRF ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.5533, mrr=0.3326
  Loading indexes with sentence-transformers/multi-qa-MiniLM-L6-cos-v1 ...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

  minsearch ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.3493, mrr=0.1699
  FAISS (multi-qa-MiniLM-L6-cos-v1) ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.5055, mrr=0.3149
  RRF ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.532, mrr=0.3114

=== Ground truth: gpt-5.6-luna (6000 pairs) ===
  Loading indexes with sentence-transformers/all-MiniLM-L6-v2 ...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

  minsearch ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.3875, mrr=0.1931
  FAISS (all-MiniLM-L6-v2) ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.5973, mrr=0.3856
  RRF ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.6092, mrr=0.381
  Loading indexes with sentence-transformers/multi-qa-MiniLM-L6-cos-v1 ...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

  minsearch ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.3875, mrr=0.1931
  FAISS (multi-qa-MiniLM-L6-cos-v1) ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.5557, mrr=0.3569
  RRF ...

  0%|          | 0/6000 [00:00<?, ?it/s]

    hit_rate=0.5815, mrr=0.3605

Saved to /Users/I556249/PycharmProjects/llm-capstone/data/retrieval-eval-results.csv

In [4]:
# Results table sorted by MRR
results_df.sort_values('mrr', ascending=False).reset_index(drop=True)

        gt_model                  embedding     method  hit_rate     mrr
0   gpt-5.6-luna           all-MiniLM-L6-v2      faiss    0.5973  0.3856
1   gpt-5.6-luna           all-MiniLM-L6-v2        rrf    0.6092  0.3810
2   gpt-5.6-luna  multi-qa-MiniLM-L6-cos-v1        rrf    0.5815  0.3605
3   gpt-5.6-luna  multi-qa-MiniLM-L6-cos-v1      faiss    0.5557  0.3569
4   gpt-5.4-mini           all-MiniLM-L6-v2      faiss    0.5407  0.3379
5   gpt-5.4-mini           all-MiniLM-L6-v2        rrf    0.5533  0.3326
6   gpt-5.4-mini  multi-qa-MiniLM-L6-cos-v1      faiss    0.5055  0.3149
7   gpt-5.4-mini  multi-qa-MiniLM-L6-cos-v1        rrf    0.5320  0.3114
8   gpt-5.6-luna           all-MiniLM-L6-v2  minsearch    0.3875  0.1931
9   gpt-5.6-luna  multi-qa-MiniLM-L6-cos-v1  minsearch    0.3875  0.1931
10  gpt-5.4-mini           all-MiniLM-L6-v2  minsearch    0.3493  0.1699
11  gpt-5.4-mini  multi-qa-MiniLM-L6-cos-v1  minsearch    0.3493  0.1699

## Boost Tuning

Systematically compare different boost weights for minsearch text fields.
Uses `gpt-5.6-luna` ground truth (best GT model) with the default embedding model.

In [7]:
import itertools

os.environ['EMBEDDING_MODEL'] = 'sentence-transformers/all-MiniLM-L6-v2'
import movie_assistant.ingest as ingest
importlib.reload(ingest)

gt_tune = pd.read_csv(ROOT / 'data/ground-truth-retrieval-gpt-5.6-luna.csv')
gt_sample = gt_tune.sample(500, random_state=42).reset_index(drop=True)
print(f'Tuning on {len(gt_sample)} questions')

TITLE_BOOSTS    = [1.0, 2.0, 3.0, 5.0]
KEYWORD_BOOSTS  = [0.5, 1.0, 2.0, 3.0]
OVERVIEW_BOOSTS = [0.5, 1.0, 1.5, 2.0]

total = len(TITLE_BOOSTS) * len(KEYWORD_BOOSTS) * len(OVERVIEW_BOOSTS)
tune_rows = []

for i, (tb, kb, ob) in enumerate(itertools.product(TITLE_BOOSTS, KEYWORD_BOOSTS, OVERVIEW_BOOSTS)):
    boost = {'title': tb, 'keywords': kb, 'overview': ob, 'tagline': 0.5, 'genres': 0.5}
    print(f'[{i+1}/{total}] title={tb}, keywords={kb}, overview={ob}', end=' ... ')
    search_fn = lambda q, b=boost, **_: ingest.search_minsearch(q, boost=b, num_results=10)
    hr, mrr = hit_rate_mrr(search_fn, gt_sample)
    print(f'hit_rate={hr}, mrr={mrr}')
    tune_rows.append({'title': tb, 'keywords': kb, 'overview': ob, 'hit_rate': hr, 'mrr': mrr})

tune_df = pd.DataFrame(tune_rows)
tune_df.to_csv(ROOT / 'data/boost-tuning-results.csv', index=False)
print(f'\nSaved {len(tune_df)} combinations')
tune_df.sort_values('mrr', ascending=False).head(10)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

Tuning on 500 questions
[1/64] title=1.0, keywords=0.5, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.324, mrr=0.1723
[2/64] title=1.0, keywords=0.5, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.452, mrr=0.2413
[3/64] title=1.0, keywords=0.5, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.554, mrr=0.3245
[4/64] title=1.0, keywords=0.5, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.6, mrr=0.378
[5/64] title=1.0, keywords=1.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.39, mrr=0.2078
[6/64] title=1.0, keywords=1.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.508, mrr=0.2851
[7/64] title=1.0, keywords=1.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.592, mrr=0.3522
[8/64] title=1.0, keywords=1.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.612, mrr=0.398
[9/64] title=1.0, keywords=2.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.434, mrr=0.2475
[10/64] title=1.0, keywords=2.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.53, mrr=0.3061
[11/64] title=1.0, keywords=2.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.592, mrr=0.3597
[12/64] title=1.0, keywords=2.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.62, mrr=0.4086
[13/64] title=1.0, keywords=3.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.442, mrr=0.2391
[14/64] title=1.0, keywords=3.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.514, mrr=0.2872
[15/64] title=1.0, keywords=3.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.568, mrr=0.335
[16/64] title=1.0, keywords=3.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.6, mrr=0.3787
[17/64] title=2.0, keywords=0.5, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.22, mrr=0.1227
[18/64] title=2.0, keywords=0.5, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.282, mrr=0.1429
[19/64] title=2.0, keywords=0.5, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.36, mrr=0.1813
[20/64] title=2.0, keywords=0.5, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.424, mrr=0.2206
[21/64] title=2.0, keywords=1.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.252, mrr=0.1316
[22/64] title=2.0, keywords=1.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.322, mrr=0.1612
[23/64] title=2.0, keywords=1.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.41, mrr=0.2016
[24/64] title=2.0, keywords=1.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.49, mrr=0.2398
[25/64] title=2.0, keywords=2.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.338, mrr=0.1657
[26/64] title=2.0, keywords=2.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.404, mrr=0.2033
[27/64] title=2.0, keywords=2.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.468, mrr=0.2392
[28/64] title=2.0, keywords=2.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.518, mrr=0.2796
[29/64] title=2.0, keywords=3.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.384, mrr=0.1966
[30/64] title=2.0, keywords=3.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.44, mrr=0.2342
[31/64] title=2.0, keywords=3.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.486, mrr=0.2596
[32/64] title=2.0, keywords=3.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.526, mrr=0.3081
[33/64] title=3.0, keywords=0.5, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.168, mrr=0.107
[34/64] title=3.0, keywords=0.5, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.202, mrr=0.1178
[35/64] title=3.0, keywords=0.5, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.238, mrr=0.1279
[36/64] title=3.0, keywords=0.5, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.286, mrr=0.1453
[37/64] title=3.0, keywords=1.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.178, mrr=0.1119
[38/64] title=3.0, keywords=1.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.216, mrr=0.1242
[39/64] title=3.0, keywords=1.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.262, mrr=0.1381
[40/64] title=3.0, keywords=1.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.318, mrr=0.158
[41/64] title=3.0, keywords=2.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.236, mrr=0.1253
[42/64] title=3.0, keywords=2.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.278, mrr=0.1417
[43/64] title=3.0, keywords=2.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.334, mrr=0.1634
[44/64] title=3.0, keywords=2.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.388, mrr=0.1842
[45/64] title=3.0, keywords=3.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.284, mrr=0.1417
[46/64] title=3.0, keywords=3.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.332, mrr=0.1674
[47/64] title=3.0, keywords=3.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.37, mrr=0.1872
[48/64] title=3.0, keywords=3.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.436, mrr=0.2149
[49/64] title=5.0, keywords=0.5, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.142, mrr=0.0984
[50/64] title=5.0, keywords=0.5, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.148, mrr=0.1035
[51/64] title=5.0, keywords=0.5, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.154, mrr=0.1063
[52/64] title=5.0, keywords=0.5, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.17, mrr=0.1094
[53/64] title=5.0, keywords=1.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.146, mrr=0.1005
[54/64] title=5.0, keywords=1.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.156, mrr=0.107
[55/64] title=5.0, keywords=1.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.162, mrr=0.1081
[56/64] title=5.0, keywords=1.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.172, mrr=0.1121
[57/64] title=5.0, keywords=2.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.152, mrr=0.1025
[58/64] title=5.0, keywords=2.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.162, mrr=0.1072
[59/64] title=5.0, keywords=2.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.174, mrr=0.1151
[60/64] title=5.0, keywords=2.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.188, mrr=0.1189
[61/64] title=5.0, keywords=3.0, overview=0.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.18, mrr=0.1095
[62/64] title=5.0, keywords=3.0, overview=1.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.198, mrr=0.1162
[63/64] title=5.0, keywords=3.0, overview=1.5 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.206, mrr=0.1231
[64/64] title=5.0, keywords=3.0, overview=2.0 ...

  0%|          | 0/500 [00:00<?, ?it/s]

hit_rate=0.246, mrr=0.135

Saved 64 combinations

    title  keywords  overview  hit_rate     mrr
11    1.0       2.0       2.0     0.620  0.4086
7     1.0       1.0       2.0     0.612  0.3980
15    1.0       3.0       2.0     0.600  0.3787
3     1.0       0.5       2.0     0.600  0.3780
10    1.0       2.0       1.5     0.592  0.3597
6     1.0       1.0       1.5     0.592  0.3522
14    1.0       3.0       1.5     0.568  0.3350
2     1.0       0.5       1.5     0.554  0.3245
31    2.0       3.0       2.0     0.526  0.3081
9     1.0       2.0       1.0     0.530  0.3061

In [9]:
best = tune_df.sort_values('mrr', ascending=False).iloc[0]
print('Best boost combination:')
print(f'  title={best.title}, keywords={best.keywords}, overview={best.overview}')
print(f'  hit_rate={best.hit_rate}, mrr={best.mrr}')

# Compare vs default boost
default_boost = {'title': 3.0, 'keywords': 2.0, 'overview': 1.5, 'tagline': 1.0, 'genres': 1.0}
default_fn = lambda q, **_: ingest.search_minsearch(q, boost=default_boost, num_results=10)
default_hr, default_mrr = hit_rate_mrr(default_fn, gt_sample)
print(f'\nDefault boost: hit_rate={default_hr}, mrr={default_mrr}')
print(f'Best boost:    hit_rate={best.hit_rate}, mrr={best.mrr}')

Best boost combination:
  title=1.0, keywords=2.0, overview=2.0
  hit_rate=0.62, mrr=0.4086

  0%|          | 0/500 [00:00<?, ?it/s]

Default boost: hit_rate=0.362, mrr=0.1821
Best boost:    hit_rate=0.62, mrr=0.4086